### ISSUE TITLE
sqlite support in the beta version

### ISSUE THREAD

**Issue by goldenbutteredjam** [anita-app/anita#7]
Can you tell me if sqlite is working in the beta version at https://anita-app.com/app/#/projects/add?

I am not able to save or open a sqlite project on this page. 

When I try to save a sqlite file I get this error in the console in Chrome.

`sql-wasm.js:40 Uncaught (in promise) Error: LinkError: WebAssembly.instantiate(): Import #34 module="a" function="I" error: function import requires a callable
    at u.onAbort (sql-wasm.js:40:20)
    at Q (sql-wasm.js:101:106)
    at sql-wasm.js:158:425`

If I try to import an existing sqlite file in Chrome, I am getting the following error.

`VM173:1 Uncaught (in promise) SyntaxError: Unexpected token 'S', "SQLite for"... is not valid JSON
    at JSON.parse (<anonymous>)
    at e.value (project-file-importer.class.ts:66:29)
    at e.<anonymous> (project-file-importer.class.ts:41:10)
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)`

**Comment by ilDon** [comment]
Hi, thank's for reporting this. I think I'll drop support for SQLite. It was an experiment, and while it would be very nice to keep it, I don't have time to support it. If you want to try fixing this with a PR, though, I'd be happy to merge the fix. It might be as simple as updating the dependencies :-)
